// Bright Avatar style gallery — reproduces the reference base and showcases the
// modular variations per category (capelli, occhi, bocche, barbe, occhiali,
// vestiti, incarnato), plus full NPCs generated by the engine in this style.
//
// Run: node --experimental-strip-types --import ./scripts/ts-resolve.mjs scripts/generate_bright_gallery.ts

import { mkdir, writeFile, rm } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import { buildBrightAvatar, BRIGHT_BG } from '../src/services/brightAvatarSvg.ts'
import { generateNpcAvatar } from '../src/services/NpcAvatarEngine.ts'
import type {
  AvatarConfig, AvatarHairStyle, EyeStyle, MouthStyle, BeardStyle,
  AvatarAccessory, AvatarClothesStyle, SkinTone, Gender,
} from '../src/store/types.ts'

const OUT_DIR = path.resolve(import.meta.dirname, '..', 'preview', 'npc-gallery', 'bright-style')

const BASE: AvatarConfig = {
  skinTone: 'light', hairStyle: 'short', hairColor: 'black',
  eyeStyle: 'round', eyeColor: 'brown', browStyle: 'medium',
  beardStyle: 'none', clothesStyle: 'casual', accessory: 'none', mouthStyle: 'smile',
}

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

// Place an avatar as a nested <svg> at (x,y) sized w.
function place(cfg: AvatarConfig, x: number, y: number, w: number, bg: string | null): string {
  const svg = buildBrightAvatar(cfg, { size: w, background: bg })
  return svg.replace('<svg xmlns="http://www.w3.org/2000/svg"', `<svg x="${x}" y="${y}"`)
}

interface Variation { label: string; cfg: AvatarConfig }
interface Band { title: string; items: Variation[] }

const BANDS: Band[] = [
  {
    title: 'Capelli (capelli)',
    items: (['bald','buzz','short','medium','long','wavy','curly','afro','ponytail','bun'] as AvatarHairStyle[])
      .map(v => ({ label: v, cfg: { ...BASE, hairStyle: v } })),
  },
  {
    title: 'Occhi (occhi)',
    items: (['round','almond','wide','narrow'] as EyeStyle[])
      .map(v => ({ label: v, cfg: { ...BASE, eyeStyle: v } })),
  },
  {
    title: 'Bocche (bocche)',
    items: (['smile','neutral','grin','smirk','frown'] as MouthStyle[])
      .map(v => ({ label: v, cfg: { ...BASE, mouthStyle: v } })),
  },
  {
    title: 'Barbe (barbe)',
    items: (['none','stubble','short','full','goatee','mustache'] as BeardStyle[])
      .map(v => ({ label: v, cfg: { ...BASE, beardStyle: v } })),
  },
  {
    title: 'Occhiali e cappelli (occhiali)',
    items: (['none','glasses_round','glasses_square','sunglasses','hat_cap','hat_beanie','hat_fedora'] as AvatarAccessory[])
      .map(v => ({ label: v, cfg: { ...BASE, accessory: v } })),
  },
  {
    title: 'Vestiti (vestiti)',
    items: (['casual','formal','sporty','elegant','punk','traditional'] as AvatarClothesStyle[])
      .map(v => ({ label: v, cfg: { ...BASE, clothesStyle: v } })),
  },
  {
    title: 'Incarnato (pelle)',
    items: (['light','medium_light','medium','medium_dark','dark'] as SkinTone[])
      .map(v => ({ label: v, cfg: { ...BASE, skinTone: v } })),
  },
]

// Full NPCs straight from the engine, drawn in bright style.
const NPCS: { name: string; gender: Gender; age: number; looks: number; happiness: number }[] = [
  { name: 'Aurora',   gender: 'female',     age: 24, looks: 88, happiness: 90 },
  { name: 'Marco',    gender: 'male',       age: 31, looks: 60, happiness: 70 },
  { name: 'Sofia',    gender: 'female',     age: 47, looks: 55, happiness: 45 },
  { name: 'Noa',      gender: 'non_binary', age: 22, looks: 75, happiness: 80 },
  { name: 'Davide',   gender: 'male',       age: 9,  looks: 70, happiness: 85 },
  { name: 'Chiara',   gender: 'female',     age: 34, looks: 92, happiness: 75 },
  { name: 'Alessandro',gender: 'male',      age: 52, looks: 50, happiness: 30 },
  { name: 'Emma',     gender: 'female',     age: 29, looks: 80, happiness: 88 },
  { name: 'Kai',      gender: 'non_binary', age: 27, looks: 72, happiness: 40 },
  { name: 'Francesco',gender: 'male',       age: 68, looks: 40, happiness: 60 },
  { name: 'Beatrice', gender: 'female',     age: 21, looks: 90, happiness: 95 },
  { name: 'Pietro',   gender: 'male',       age: 26, looks: 84, happiness: 55 },
]

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true })
  await mkdir(OUT_DIR, { recursive: true })

  // Standalone base reproduction.
  await writeFile(path.join(OUT_DIR, 'base.svg'), buildBrightAvatar(BASE, { size: 256, background: '#5F5AA2' }), 'utf8')
  await sharp(Buffer.from(buildBrightAvatar(BASE, { size: 256, background: '#5F5AA2' }))).png().toFile(path.join(OUT_DIR, 'base.png'))

  // ---- Variations contact sheet ----
  const CELL = 132, GAP = 8, LABEL_H = 26, TITLE_H = 30, PAD = 24
  const maxCols = Math.max(...BANDS.map(b => b.items.length))
  const W = PAD * 2 + maxCols * (CELL + GAP)
  const bandH = TITLE_H + CELL + LABEL_H
  const npcRows = Math.ceil(NPCS.length / 6)
  const npcH = TITLE_H + npcRows * (CELL + LABEL_H)
  const H = 80 + BANDS.length * bandH + npcH + PAD

  let s = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">`
  s += `<rect width="${W}" height="${H}" fill="#0f0c1d"/>`
  s += `<text x="${W / 2}" y="44" text-anchor="middle" fill="#fff" font-family="Inter, Arial, sans-serif" font-size="28" font-weight="800">Bright Avatar — variazioni modulari</text>`
  s += `<text x="${W / 2}" y="68" text-anchor="middle" fill="#a78bfa" font-family="Inter, Arial, sans-serif" font-size="14">Basato sul riferimento fornito · stesso AvatarConfig dell'engine NPC</text>`

  let y = 80
  const font = 'Inter, Arial, sans-serif'
  for (const band of BANDS) {
    s += `<text x="${PAD}" y="${y + 20}" fill="#fff" font-family="${font}" font-size="17" font-weight="700">${esc(band.title)}</text>`
    let x = PAD
    const cy = y + TITLE_H
    for (const it of band.items) {
      const bg = BRIGHT_BG[(it.label.length + x) % BRIGHT_BG.length]
      s += place(it.cfg, x, cy, CELL, bg)
      s += `<text x="${x + CELL / 2}" y="${cy + CELL + 16}" text-anchor="middle" fill="#c4b5fd" font-family="${font}" font-size="11.5">${esc(it.label)}</text>`
      x += CELL + GAP
    }
    y += bandH
  }

  // ---- Full NPC grid ----
  s += `<text x="${PAD}" y="${y + 20}" fill="#fff" font-family="${font}" font-size="17" font-weight="700">NPC completi (generati dall'engine)</text>`
  const ny = y + TITLE_H
  NPCS.forEach((npc, i) => {
    const seed = `bright-${npc.name.toLowerCase()}`
    const cfg = generateNpcAvatar(seed, npc.gender, { age: npc.age, looks: npc.looks, happiness: npc.happiness })
    const col = i % 6, row = Math.floor(i / 6)
    const x = PAD + col * (CELL + GAP)
    const cy = ny + row * (CELL + LABEL_H)
    const bg = BRIGHT_BG[i % BRIGHT_BG.length]
    s += place(cfg, x, cy, CELL, bg)
    s += `<text x="${x + CELL / 2}" y="${cy + CELL + 16}" text-anchor="middle" fill="#c4b5fd" font-family="${font}" font-size="12">${esc(npc.name)} · ${npc.age}a</text>`
  })

  s += `</svg>`
  await writeFile(path.join(OUT_DIR, 'variations-sheet.svg'), s, 'utf8')
  await sharp(Buffer.from(s)).png().toFile(path.join(OUT_DIR, 'variations-sheet.png'))

  // ---- index.html ----
  const section = (title: string, items: { label: string; cfg: AvatarConfig; bg: string }[]) =>
    `<h2>${esc(title)}</h2><div class="grid">` + items.map(it =>
      `<figure><div class="av">${buildBrightAvatar(it.cfg, { size: 130, background: it.bg })}</div><figcaption>${esc(it.label)}</figcaption></figure>`
    ).join('') + `</div>`

  let html = `<!doctype html><html lang="it"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>Bright Avatar — Variazioni</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; padding:32px; background:#0f0c1d; color:#fff; font-family:Inter, system-ui, Arial, sans-serif; }
  h1 { margin:0 0 4px; } p.sub { color:#a78bfa; margin:0 0 24px; }
  h2 { margin:28px 0 12px; font-size:18px; border-bottom:1px solid rgba(167,139,250,0.25); padding-bottom:6px; }
  .grid { display:flex; flex-wrap:wrap; gap:14px; }
  figure { margin:0; text-align:center; }
  .av svg { border-radius:14px; display:block; }
  figcaption { margin-top:6px; color:#c4b5fd; font-size:12px; }
</style></head><body>
<h1>Bright Avatar — Variazioni modulari</h1>
<p class="sub">Basato sul riferimento fornito · ${BANDS.reduce((n,b)=>n+b.items.length,0)} variazioni + ${NPCS.length} NPC completi.</p>`
  for (const band of BANDS) {
    html += section(band.title, band.items.map((it, i) => ({ label: it.label, cfg: it.cfg, bg: BRIGHT_BG[i % BRIGHT_BG.length] })))
  }
  html += section('NPC completi (engine)', NPCS.map((npc, i) => ({
    label: `${npc.name} · ${npc.age}a`,
    cfg: generateNpcAvatar(`bright-${npc.name.toLowerCase()}`, npc.gender, { age: npc.age, looks: npc.looks, happiness: npc.happiness }),
    bg: BRIGHT_BG[i % BRIGHT_BG.length],
  })))
  html += `</body></html>`
  await writeFile(path.join(OUT_DIR, 'index.html'), html, 'utf8')

  const totalVars = BANDS.reduce((n, b) => n + b.items.length, 0)
  console.log(`Bright gallery: ${totalVars} variazioni + ${NPCS.length} NPC → ${OUT_DIR}`)
}

main().catch(err => { console.error(err); process.exit(1) })
